# Generated by Django 4.2.7 on 2023-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
